### ISSUE TITLE
HALCON 12 support

### ISSUE THREAD

**Issue by drewm1980** [dov/hirsch#4]
This looks great and I would love to use it in HALCON 12!

I get about halfway through the hirsch build process; I can generate the .i files, but when I do 

> sudo python setup.py install 

I get:

```
...
src/pyhimage.cc: In function ‘PyObject* PyHirschImage__interface_get(PyObject*)’:
src/pyhimage.cc:242:71: error: no matching function for call to ‘Halcon::HImage::GetImagePointer1(Halcon::HTuple*, Halcon::HTuple*, Halcon::HTuple*)’
     void *buf = (void*)image->GetImagePointer1(&IType,&IWidth,&IHeight);
                                                                       ^
src/pyhimage.cc:242:71: note: candidate is:
In file included from /opt/halcon/include/cpp/HalconCpp.h:249:0,
                 from src/pyhpoint2d.h:6,
                 from src/pyhirsch.h:23,
                 from src/pyhimage.cc:3:
/opt/halcon/include/cpp/HImage.h:458:17: note: virtual Hlong Halcon::HImage::GetImagePointer1(char*, Hlong*, Hlong*) const
   virtual Hlong GetImagePointer1(char *Type, Hlong *Width, Hlong *Height) const;
                 ^
/opt/halcon/include/cpp/HImage.h:458:17: note:   no known conversion for argument 1 from ‘Halcon::HTuple*’ to ‘char*’

```

Unfortunately, MVTec re-did their c++ bindings, so hirsch will be even more broken in HALCON 13, but if anyone has had any luck with anything newer than HALCON 9, please post about it!

Thanks! Andrew

**Comment by dov** [comment]
Unfortunately I don't have access to anything newer than Halcon 9. If someone would sponsor a newer license for me, I might try to get update the bindings. :-)

Regarding the particular compilation error, it occurs in one of the functions that is not autogenerated. My idea of the binding was to support manual bindings where the automatic translation was not sufficient. The particular error occurs in the array (numpy) interface function, which tries to use the HImage method GetImagePointer1 to get a pointer to the raw data. Apparantly this function has changed its interface, so you will need to solve it together with the halcon C++ documentation.

Good luck!
Dov

**Comment by drewm1980** [comment]
I had some partial success! 

With some modified calls to GetImagePointer1 I can build the bindings, and test-barcode.py works, but test-with-numpy segfaults. 

This is not surprising, since I have no clue how either HALCON or hirsch do memory management, and there are no fancy new pointer types to save me by enforcing correctness. 

I'll push what I have to my fork; perhaps the error is blindingly obvious to someone who's more familiar with HALCON memory management.

**Comment by drewm1980** [comment]
I can't seem to figure out how to trap the segfault...

> $ python -m pdb test-with-numpy.py

doesn't trap the segfault

> gdb -ex r --args python test-with-numpy.py

 just hangs

**Comment by dov** [comment]
Try building the python module with 

    env CFLAGS='-O0 -g' python setup.py build --debug

and then run gdb 

    gdb python

and set a break point in `PyHirschImage_getbuffer()` and do:

    run test-with-numpy

**Comment by drewm1980** [comment]
Hmmm, I didn't know switching on debug symbols affects the interuptibility of the program, but I can now Ctrl-c out of the hung python in gdb. Here's where it is stuck:

```
^C[New Thread 0x7ffff41ab700 (LWP 7056)]

Program received signal SIGINT, Interrupt.
[Switching to Thread 0x7ffff49ac700 (LWP 7055)]
pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185     ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff4d8910b in ?? () from /usr/lib/libblas.so.3
#2  0x00007ffff7bc4182 in start_thread (arg=0x7ffff49ac700) at pthread_create.c:312
#3  0x00007ffff78f147d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) 
```

Inspecting where the other threads are:
```
(gdb) thread 1
[Switching to thread 1 (Thread 0x7ffff7fb7740 (LWP 7049))]
#0  __GI___pthread_mutex_init (mutex=0x7ffff61ad090, mutexattr=<optimized out>) at pthread_mutex_init.c:84
84      pthread_mutex_init.c: No such file or directory.
(gdb) thread 2
[Switching to thread 2 (Thread 0x7ffff49ac700 (LWP 7055))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185     ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
(gdb) thread 3
[Switching to thread 3 (Thread 0x7ffff41ab700 (LWP 7056))]
#0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
95      ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
```

So this deadlock seems like a different bug that only happens  in the debugger; I'm still not trapping the segfault that I get in python...

**Comment by dov** [comment]
Solved in the halcon13 branch.
