### ISSUE TITLE
Halcon13 Updates?

### ISSUE THREAD

**Issue by gachiemchiep** [dov/hirsch#9]
Hello sir. 
Is there any paln to update this library to Halcon 13

**Comment by dov** [comment]
There already is a halcon13 branch. Please test it and file separate issues.

The chances that I will fix anything is pretty low as I don't have access to a halcon13 license.

**Comment by gachiemchiep** [comment]
I see the branch.
Currently i have halcon 13 so if something nasty happen i could upload patch.
